### ISSUE TITLE
Ascii listing 

### ISSUE THREAD

**Issue by jeromelesaux** [cpcsdk/idsk#1]
Hi 
I added for my needs, the ascii export file. 
Are you interested in ? 
If so think the modified files in attached files
[idsk-patch.zip](https://github.com/cpcsdk/idsk/files/2016662/idsk-patch.zip)

**Comment by rgiot** [comment]
Hello,
why not. Please could you provide a pull request ? It will be easier to look at the differences before accepting them.
Thanks

**Comment by jeromelesaux** [comment]
done

**Comment by rgiot** [comment]
Ok. I have seen some French text, but it seems it is also the case with the original code. Has we have no test suite, I'll make some tries this evening to check standard cases are not broken (or add some tests).

I'll let @pulkomandy  make a quick pass on the code also before merging

**Comment by jeromelesaux** [comment]
Ok let me know ;).
Regards

**Comment by pulkomandy** [comment]
Looks ok. It would be nicer to convert the AMSDOS character set to UTF-8, but we can add that later.

@rgiot: Jérôme is the original author of iDSK, why should I review the code here? :)

**Comment by jeromelesaux** [comment]
Yep that's me :D.
If you want I can convert the char set (up to you).

**Comment by rgiot** [comment]
Ok, I have blindly merged the code. I have started to write test but they do not test yet previous options
@pulkomandy I do less and less C++, more and more Rust => I'm less confident with this language :(
