### ISSUE TITLE
Corrupt DSK on Windows / Big Endian detection doesn't work with Visual Studio 16 / 2019

### ISSUE THREAD

**Issue by gschizas** [cpcsdk/idsk#15]
While compiling with Visual Studio 2019 Community Edition (the latest released Visual Studio at the time of the writing), iDSK doesn't recognize known good .dsk files (or .dsk files created on a Linux machine) with the following message:

    DSK has wrong sector number!

Even when creating a blank DSK file, it is corrupted, with a lot of `CC` where `00` should be.

I've narrowed the problem down to the big endian detection, by adding the following code in Main.cpp

	if (isBigEndian()) {
		cerr << "Yes" << endl;
	}
	else {
		cerr << "No" << endl;
	}
	exit(EXIT_SUCCESS);

When compiling, I'm getting `Yes` on 64-bit Windows. I'm getting `No` on a 64-bit Linux.

After negating the result of `isBigEndian` on Windows, everything seems to work ok.

I'm guessing the semantics are flipped, and the `isBigEndian` function should always return `false` on Windows (and be actually called `isLittleEndian` instead. But not having access to any actual little endian machine, I'm not able to test that the semantics mean what I think they mean.

I'll be uploading a PR soon.

**Comment by pulkomandy** [comment]
Yes, it seems I was not careful enough when writing this function. Thanks for the patch!

**Comment by gschizas** [comment]
Maybe I was too quick to create the patch. I'm still seeing the same problem right now, even though `iDSK.exe` does read known good disks now.

I'll do some more research.

In my original patch (a long time ago - never uploaded anywhere), I had commented out all 4 references to `isBigEndian` to make `iDSK.exe` work.

What machines is this compilable on?

**Comment by pulkomandy** [comment]
I only use it on Haiku (on x86 PC).

The big endian code in iDSK was originally added for Mac OS X PowerPC support and may still be used by the MorphOS version.

Depending on your needs, you may have better luck with https://github.com/cpcsdk/cpctools/tree/master/cpctools/tools/cpcfs

It would be nice to have a single tool combining the capabilities of both, but I never had time to do that...

**Comment by gschizas** [comment]
Oh, I have used cpcfs as well (and cpcxfs). It's just that iDSK is part of @llopis [Amstrad Diagnostics](https://github.com/llopis/amstrad-diagnostics)' build process, but mostly I'm just curious on how to check if the function name is indeed "does this require a big/little swap".

I guess I'll try my hand with QEmu

**Comment by pulkomandy** [comment]
It should be, but this codebase is not great and there are many bugs :(

I only use cpcfs in my own projects and so I did not put a lot of efforts in improving it.

**Comment by gschizas** [comment]
Ok, found the problem. It was unrelated to this, so this issue is rightfully closed. I'll open a new issue and PR tomorrow.
