### ISSUE TITLE
Please add a licence.

### ISSUE THREAD

**Issue by bignaux** [cpcsdk/idsk#6]
and if you can do a release tag, i would be fine.

**Comment by pulkomandy** [comment]
That would be great, but we'll have to get agreement from the original author and everyone who contributed since.

**Comment by bignaux** [comment]
since they have contribute without any licence, we could assume MIT or WTFPL ?

**Comment by pulkomandy** [comment]
Not at all. Code with no license is not redistributable and we are not allowed to modify it. It shouldn't even be here if we stick to strictly legal terms.

Moreover, some of the original code is from CPCEmu, for which the license does not allow anything: http://www.cpc-emu.org/licence.html

So we need agreement from Marco Vieth, Ludovic Deplanque and Sid, as well as all contributors listed here (personally, I'm fine with MIT for the parts I worked on)

I suggest using cpcfs instead from https://github.com/cpcsdk/cpctools/tree/master/cpctools/tools/cpcfs
This one has a license at the end of the README (https://github.com/cpcsdk/cpctools/tree/master/cpctools):

> You can use these tools freely. 
> You can also modify all source code or include them into your own production
> (small credit will be enough ! ;).

Which is close enough to MIT.

**Comment by bignaux** [comment]
That's why on nixos, i put licence to "unknown" but that makes the software proprietary and need people accept such software explicitly in their configuration and makes it non distributive on our infra. Seems hard to get credit from all the people you mentioned. Let it be.

**Comment by pulkomandy** [comment]
I'll see what I can do but I need to search my old address books for contact address. Leaving the ticket open in case I can make some progress on this.

* [ ] Marco Vieth contacted through cpcemu website (I hope that contact form from 10 years ago still goes somewhere)
* [x] Demoniak / Ludivic Deplanque contacted through old email address from latest PC-CPC release
* [x] Sid contacted through github below

**Comment by pulkomandy** [comment]
@jlsaxione We would appreciate your agreement here. Is MIT fine for you?

**Comment by jlsaxione** [comment]
fine for me feel free to add this licence.

**Comment by pulkomandy** [comment]
@rgiot @ColinPitrat @miniupnp there is some code from you in this repo, are you fine with a relicense to MIT?

**Comment by ColinPitrat** [comment]
OK for me.

**Comment by miniupnp** [comment]
yes

**Comment by pulkomandy** [comment]
I got a reply from Demoniak by e-mail. So we're only missing Krusty (rgiot) and Marco Vieth now.

**Comment by rgiot** [comment]
Do as you wish
